// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU4JXvwmwKFNX0QhzrzjDq3z3vlv4oJlw',
    appId: '1:757470972965:android:1182cc1b98fa54eae403cc',
    messagingSenderId: '757470972965',
    projectId: 'mini-ecommerce-ce1d8',
    storageBucket: 'mini-ecommerce-ce1d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfrBis1Si3veOpsYrPdRunjwqljmRR7-o',
    appId: '1:757470972965:ios:9ac3bde07daffce7e403cc',
    messagingSenderId: '757470972965',
    projectId: 'mini-ecommerce-ce1d8',
    storageBucket: 'mini-ecommerce-ce1d8.firebasestorage.app',
    androidClientId:
        '757470972965-7b3mvdme2uhtsa29aedc4vkm3rndlfv0.apps.googleusercontent.com',
    iosClientId:
        '757470972965-pc5lo01e2bdcqh8k1daa4bmi8869v7ej.apps.googleusercontent.com',
    iosBundleId: 'com.zaid.minishop',
  );
}
